[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
cronos_testnet = "https://evm-t3.cronos.org"
cronos_mainnet = "https://evm.cronos.org"

[etherscan]
cronos_testnet = { key = "${CRONOSCAN_API_KEY}", url = "https://cronos.org/explorer/testnet3/api" }
cronos_mainnet = { key = "${CRONOSCAN_API_KEY}", url = "https://api.cronoscan.com/api" }
